import classes from './layout.module.scss'
import type { Metadata } from 'next'
import './globals.scss'
import MenuButton from './components/MenuButton/MenuButton'
import StoreProvider from './components/StoreProvider/StoreProvider'
import { useAppSelector } from './lib/redux/hooks'
import localFont from 'next/font/local'
import Header from './components/Header/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Gilroy = localFont({
  src: './styles/fonts/Gilroy/Gilroy-Medium.woff2',
  display: 'swap',
  variable: '--font-Gilroy'
})

export default function RootLayout(props: {
  children: React.ReactNode,
}) {

  return (
 <html lang="en" className={Gilroy.variable}>
      <body>
        <StoreProvider>
        <Header/>
        <main className={classes.Content}>
        {props.children}
        </main>
        </StoreProvider>
      </body>
    </html>
  )
}
